name: Mirror to Remote Gitlab Repository

on:
    push:
        branches:
            - main

jobs:
    mirror:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                    fetch-depth: 0
            
            - uses: yesolutions/mirror-action@master
              with:
                REMOTE: 'https://gitlab.eduxiji.net/T202411065203807/chilletcompiler.git'
                GIT_USERNAME: ${{ vars.GIT_USERNAME }}
                GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
                PUSH_ALL_REFS: "false"
                DEBUG: "true"